"""시스템 프롬프트 모듈"""

from .system_prompts import (
    CAREER_SYSTEM_PROMPT,
    FORTUNE_SYSTEM_PROMPT,
    HEALTH_SYSTEM_PROMPT,
    ORCHESTRATOR_SYSTEM_PROMPT,
    PERSONALITY_SYSTEM_PROMPT,
    RELATIONSHIP_SYSTEM_PROMPT,
    SYNTHESIS_SYSTEM_PROMPT,
)
